## 赛题理解

### 赛题概况
赛题以金融风控为背景，目标是预测用户贷款是否违约，提供来自某信贷平台的贷款记录，总数据量超过120w，经过抽取和脱敏后，参赛者可以下载的数据如下：
train.csv（80万条数据）、testA.csv（20万条数据）、sample_submit.csv（提交文件示例），另有testB.csv（20万条数据）作为未公开测试集，训练集中包含47列变量信息，其中15列为匿名变量。

### 数据概况
各个字段的含义参见： https://tianchi.aliyun.com/competition/entrance/531830/information

下面来看数据样例

In [4]:
import pandas as pd
train_data = pd.read_csv("./train.csv", encoding='utf-8')
train_data.head()

,id,loanAmnt,term,interestRate,installment,grade,subGrade,employmentTitle,employmentLength,homeOwnership,...,n5,n6,n7,n8,n9,n10,n11,n12,n13,n14
0,0,35000.0,5,19.52,917.97,E,E2,320.0,2 years,2,...,9.0,8.0,4.0,12.0,2.0,7.0,0.0,0.0,0.0,2.0
1,1,18000.0,5,18.49,461.90,D,D2,219843.0,5 years,0,...,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN
2,2,12000.0,5,16.99,298.17,D,D3,31698.0,8 years,0,...,0.0,21.0,4.0,5.0,3.0,11.0,0.0,0.0,0.0,4.0
3,3,11000.0,3,7.26,340.96,A,A4,46854.0,10+ years,1,...,16.0,4.0,7.0,21.0,6.0,9.0,0.0,0.0,0.0,1.0
4,4,3000.0,3,12.99,101.07,C,C2,54.0,NaN,1,...,4.0,9.0,10.0,15.0,7.0,12.0,0.0,0.0,0.0,4.0

可以看到，训练集包含47个字段，字段的数据类型不是完全相同，有缺失值存在，这在后续EDA部分处理。

### 评估指标
本赛题使用AUC（Area Under Curve）作为赛题的评估指标，其包含两方面的含义
- AUC反映的是模型对正负样本排序能力的强弱，对正负类分类的得分精度没有要求
- AUC越高，ROC曲线越靠近（0，1）点，模型排序能力越强

参见：https://zhuanlan.zhihu.com/p/57501232

### 解题思路
一般来说，解题思路可以总结如下：
1. 赛题理解（理解赛题背景、评估指标，数据字段意义等）
2. EDA（缺失值，异常值，相关性，数据分布）
3. 特征工程（专业知识理解，特征选择、降维、生成、优化）
4. 模型训练（分类or回归，模型选择，参数调优）
5. 模型融合（vote, bagging，boosting，Averaging，ranking，blending，stacking）